-- TERMÔMETRO CABANA V2.0
-- Execute no SQL Editor do Supabase.
create table if not exists public.termometro_respostas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sector text not null,
  score integer not null check (score between 1 and 5),
  reason text
);

alter table public.termometro_respostas enable row level security;

-- Remova políticas antigas se estiver repetindo a instalação.
drop policy if exists "anon_insert_termometro" on public.termometro_respostas;
drop policy if exists "auth_select_termometro" on public.termometro_respostas;

-- O terminal do funcionário pode somente inserir uma resposta.
create policy "anon_insert_termometro"
on public.termometro_respostas
for insert
to anon
with check (
  score between 1 and 5
  and char_length(sector) between 1 and 120
  and (reason is null or char_length(reason) between 1 and 120)
);

-- Somente usuário autenticado pode consultar o histórico.
create policy "auth_select_termometro"
on public.termometro_respostas
for select
to authenticated
using (true);

grant insert on public.termometro_respostas to anon;
grant select on public.termometro_respostas to authenticated;
grant usage, select on sequence public.termometro_respostas_id_seq to anon, authenticated;

-- IMPORTANTE:
-- Crie o usuário administrador em Authentication > Users.
-- Não coloque secret/service_role key no GitHub ou no navegador.
